from database import SessionLocal
import models


questions = [
    {
        "question_text": "Choose the synonym of 'Happy'.",
        "category": "Verbal Ability",
        "option_a": "Sad",
        "option_b": "Joyful",
        "option_c": "Angry",
        "option_d": "Tired",
        "correct_answer": "B",
        "difficulty": "Easy",
    },
    {
        "question_text": "Choose the antonym of 'Brave'.",
        "category": "Verbal Ability",
        "option_a": "Courageous",
        "option_b": "Bold",
        "option_c": "Cowardly",
        "option_d": "Strong",
        "correct_answer": "C",
        "difficulty": "Easy",
    },
    {
        "question_text": "Choose the correctly spelled word.",
        "category": "Verbal Ability",
        "option_a": "Recieve",
        "option_b": "Receive",
        "option_c": "Receeve",
        "option_d": "Receve",
        "correct_answer": "B",
        "difficulty": "Easy",
    },
    {
        "question_text": "Fill in the blank: She ___ to school every day.",
        "category": "Verbal Ability",
        "option_a": "go",
        "option_b": "going",
        "option_c": "goes",
        "option_d": "gone",
        "correct_answer": "C",
        "difficulty": "Easy",
    },
    {
        "question_text": "Choose the synonym of 'Rapid'.",
        "category": "Verbal Ability",
        "option_a": "Slow",
        "option_b": "Fast",
        "option_c": "Weak",
        "option_d": "Late",
        "correct_answer": "B",
        "difficulty": "Easy",
    },
    {
        "question_text": "Choose the antonym of 'Ancient'.",
        "category": "Verbal Ability",
        "option_a": "Old",
        "option_b": "Historic",
        "option_c": "Modern",
        "option_d": "Past",
        "correct_answer": "C",
        "difficulty": "Easy",
    },
    {
        "question_text": "Choose the correct article: He is ___ honest man.",
        "category": "Verbal Ability",
        "option_a": "a",
        "option_b": "an",
        "option_c": "the",
        "option_d": "no article",
        "correct_answer": "B",
        "difficulty": "Easy",
    },
    {
        "question_text": "Choose the correctly spelled word.",
        "category": "Verbal Ability",
        "option_a": "Necessary",
        "option_b": "Necesary",
        "option_c": "Neccessary",
        "option_d": "Necassary",
        "correct_answer": "A",
        "difficulty": "Easy",
    },
    {
        "question_text": "Fill in the blank: They ___ playing cricket.",
        "category": "Verbal Ability",
        "option_a": "is",
        "option_b": "are",
        "option_c": "was",
        "option_d": "be",
        "correct_answer": "B",
        "difficulty": "Easy",
    },
    {
        "question_text": "Choose the synonym of 'Begin'.",
        "category": "Verbal Ability",
        "option_a": "Start",
        "option_b": "End",
        "option_c": "Stop",
        "option_d": "Finish",
        "correct_answer": "A",
        "difficulty": "Easy",
    },

    {
        "question_text": "Choose the antonym of 'Expand'.",
        "category": "Verbal Ability",
        "option_a": "Increase",
        "option_b": "Grow",
        "option_c": "Contract",
        "option_d": "Extend",
        "correct_answer": "C",
        "difficulty": "Easy",
    },
    {
        "question_text": "Choose the correct sentence.",
        "category": "Verbal Ability",
        "option_a": "She don't like tea.",
        "option_b": "She doesn't like tea.",
        "option_c": "She doesn't likes tea.",
        "option_d": "She not like tea.",
        "correct_answer": "B",
        "difficulty": "Easy",
    },
    {
        "question_text": "Choose the synonym of 'Intelligent'.",
        "category": "Verbal Ability",
        "option_a": "Foolish",
        "option_b": "Clever",
        "option_c": "Weak",
        "option_d": "Lazy",
        "correct_answer": "B",
        "difficulty": "Easy",
    },
    {
        "question_text": "Choose the antonym of 'Victory'.",
        "category": "Verbal Ability",
        "option_a": "Success",
        "option_b": "Win",
        "option_c": "Defeat",
        "option_d": "Achievement",
        "correct_answer": "C",
        "difficulty": "Easy",
    },
    {
        "question_text": "Fill in the blank: I have lived here ___ 2018.",
        "category": "Verbal Ability",
        "option_a": "for",
        "option_b": "since",
        "option_c": "from",
        "option_d": "by",
        "correct_answer": "B",
        "difficulty": "Easy",
    },
    {
        "question_text": "Choose the correct plural of 'Child'.",
        "category": "Verbal Ability",
        "option_a": "Childs",
        "option_b": "Childes",
        "option_c": "Children",
        "option_d": "Childrens",
        "correct_answer": "C",
        "difficulty": "Easy",
    },
    {
        "question_text": "Choose the synonym of 'Difficult'.",
        "category": "Verbal Ability",
        "option_a": "Easy",
        "option_b": "Hard",
        "option_c": "Simple",
        "option_d": "Clear",
        "correct_answer": "B",
        "difficulty": "Easy",
    },
    {
        "question_text": "Choose the antonym of 'Generous'.",
        "category": "Verbal Ability",
        "option_a": "Kind",
        "option_b": "Helpful",
        "option_c": "Selfish",
        "option_d": "Giving",
        "correct_answer": "C",
        "difficulty": "Easy",
    },
    {
        "question_text": "Choose the correctly spelled word.",
        "category": "Verbal Ability",
        "option_a": "Environment",
        "option_b": "Enviroment",
        "option_c": "Envirnment",
        "option_d": "Environmant",
        "correct_answer": "A",
        "difficulty": "Easy",
    },
    {
        "question_text": "Fill in the blank: The sun ___ in the east.",
        "category": "Verbal Ability",
        "option_a": "rise",
        "option_b": "rises",
        "option_c": "rising",
        "option_d": "rose",
        "correct_answer": "B",
        "difficulty": "Easy",
    },

    {
        "question_text": "Choose the synonym of 'Abundant'.",
        "category": "Verbal Ability",
        "option_a": "Scarce",
        "option_b": "Plentiful",
        "option_c": "Limited",
        "option_d": "Rare",
        "correct_answer": "B",
        "difficulty": "Medium",
    },
    {
        "question_text": "Choose the antonym of 'Permanent'.",
        "category": "Verbal Ability",
        "option_a": "Lasting",
        "option_b": "Fixed",
        "option_c": "Temporary",
        "option_d": "Stable",
        "correct_answer": "C",
        "difficulty": "Medium",
    },
    {
        "question_text": "Choose the correct sentence.",
        "category": "Verbal Ability",
        "option_a": "Neither of the boys are ready.",
        "option_b": "Neither of the boys is ready.",
        "option_c": "Neither boys is ready.",
        "option_d": "Neither boys are ready.",
        "correct_answer": "B",
        "difficulty": "Medium",
    },
    {
        "question_text": "Choose the synonym of 'Precise'.",
        "category": "Verbal Ability",
        "option_a": "Accurate",
        "option_b": "Wrong",
        "option_c": "Approximate",
        "option_d": "Unclear",
        "correct_answer": "A",
        "difficulty": "Medium",
    },
    {
        "question_text": "Choose the antonym of 'Optimistic'.",
        "category": "Verbal Ability",
        "option_a": "Hopeful",
        "option_b": "Positive",
        "option_c": "Pessimistic",
        "option_d": "Confident",
        "correct_answer": "C",
        "difficulty": "Medium",
    },
    {
        "question_text": "Fill in the blank: She is good ___ mathematics.",
        "category": "Verbal Ability",
        "option_a": "in",
        "option_b": "at",
        "option_c": "on",
        "option_d": "with",
        "correct_answer": "B",
        "difficulty": "Medium",
    },
    {
        "question_text": "Choose the correctly spelled word.",
        "category": "Verbal Ability",
        "option_a": "Accommodation",
        "option_b": "Acommodation",
        "option_c": "Accomodation",
        "option_d": "Acomodation",
        "correct_answer": "A",
        "difficulty": "Medium",
    },
    {
        "question_text": "Choose the synonym of 'Reluctant'.",
        "category": "Verbal Ability",
        "option_a": "Willing",
        "option_b": "Unwilling",
        "option_c": "Excited",
        "option_d": "Eager",
        "correct_answer": "B",
        "difficulty": "Medium",
    },
    {
        "question_text": "Choose the antonym of 'Transparent'.",
        "category": "Verbal Ability",
        "option_a": "Clear",
        "option_b": "Visible",
        "option_c": "Opaque",
        "option_d": "Bright",
        "correct_answer": "C",
        "difficulty": "Medium",
    },
    {
        "question_text": "Choose the correct sentence.",
        "category": "Verbal Ability",
        "option_a": "He has went home.",
        "option_b": "He have gone home.",
        "option_c": "He has gone home.",
        "option_d": "He gone home.",
        "correct_answer": "C",
        "difficulty": "Medium",
    },

    {
        "question_text": "Choose the synonym of 'Obsolete'.",
        "category": "Verbal Ability",
        "option_a": "Modern",
        "option_b": "Outdated",
        "option_c": "Current",
        "option_d": "New",
        "correct_answer": "B",
        "difficulty": "Medium",
    },
    {
        "question_text": "Choose the antonym of 'Artificial'.",
        "category": "Verbal Ability",
        "option_a": "Natural",
        "option_b": "Synthetic",
        "option_c": "Man-made",
        "option_d": "Fake",
        "correct_answer": "A",
        "difficulty": "Medium",
    },
    {
        "question_text": "Fill in the blank: If I ___ rich, I would travel the world.",
        "category": "Verbal Ability",
        "option_a": "am",
        "option_b": "was",
        "option_c": "were",
        "option_d": "be",
        "correct_answer": "C",
        "difficulty": "Medium",
    },
    {
        "question_text": "Choose the synonym of 'Cautious'.",
        "category": "Verbal Ability",
        "option_a": "Careless",
        "option_b": "Careful",
        "option_c": "Reckless",
        "option_d": "Hasty",
        "correct_answer": "B",
        "difficulty": "Medium",
    },
    {
        "question_text": "Choose the antonym of 'Hostile'.",
        "category": "Verbal Ability",
        "option_a": "Aggressive",
        "option_b": "Unfriendly",
        "option_c": "Friendly",
        "option_d": "Angry",
        "correct_answer": "C",
        "difficulty": "Medium",
    },
    {
        "question_text": "Choose the correctly spelled word.",
        "category": "Verbal Ability",
        "option_a": "Privilege",
        "option_b": "Privelege",
        "option_c": "Priviledge",
        "option_d": "Privilage",
        "correct_answer": "A",
        "difficulty": "Medium",
    },
    {
        "question_text": "Choose the correct sentence.",
        "category": "Verbal Ability",
        "option_a": "Each student have a book.",
        "option_b": "Each student has a book.",
        "option_c": "Each students has a book.",
        "option_d": "Each students have a book.",
        "correct_answer": "B",
        "difficulty": "Medium",
    },
    {
        "question_text": "Choose the synonym of 'Evident'.",
        "category": "Verbal Ability",
        "option_a": "Hidden",
        "option_b": "Obvious",
        "option_c": "Doubtful",
        "option_d": "Uncertain",
        "correct_answer": "B",
        "difficulty": "Medium",
    },
    {
        "question_text": "Choose the antonym of 'Flexible'.",
        "category": "Verbal Ability",
        "option_a": "Adaptable",
        "option_b": "Rigid",
        "option_c": "Adjustable",
        "option_d": "Soft",
        "correct_answer": "B",
        "difficulty": "Medium",
    },

    {
        "question_text": "Choose the synonym of 'Meticulous'.",
        "category": "Verbal Ability",
        "option_a": "Careless",
        "option_b": "Careful",
        "option_c": "Hasty",
        "option_d": "Lazy",
        "correct_answer": "B",
        "difficulty": "Hard",
    },
    {
        "question_text": "Choose the antonym of 'Benevolent'.",
        "category": "Verbal Ability",
        "option_a": "Kind",
        "option_b": "Compassionate",
        "option_c": "Malevolent",
        "option_d": "Helpful",
        "correct_answer": "C",
        "difficulty": "Hard",
    },
    {
        "question_text": "Choose the correct meaning of the idiom 'Break the ice'.",
        "category": "Verbal Ability",
        "option_a": "Break something",
        "option_b": "Start a friendly conversation",
        "option_c": "Create a problem",
        "option_d": "End a meeting",
        "correct_answer": "B",
        "difficulty": "Hard",
    },
    {
        "question_text": "Choose the correct meaning of 'Once in a blue moon'.",
        "category": "Verbal Ability",
        "option_a": "Very frequently",
        "option_b": "Never",
        "option_c": "Very rarely",
        "option_d": "Every month",
        "correct_answer": "C",
        "difficulty": "Hard",
    },
    {
        "question_text": "Choose the synonym of 'Pragmatic'.",
        "category": "Verbal Ability",
        "option_a": "Practical",
        "option_b": "Imaginary",
        "option_c": "Unrealistic",
        "option_d": "Emotional",
        "correct_answer": "A",
        "difficulty": "Hard",
    },
    {
        "question_text": "Choose the antonym of 'Ambiguous'.",
        "category": "Verbal Ability",
        "option_a": "Unclear",
        "option_b": "Vague",
        "option_c": "Clear",
        "option_d": "Doubtful",
        "correct_answer": "C",
        "difficulty": "Hard",
    },
    {
        "question_text": "Choose the correct meaning of 'A blessing in disguise'.",
        "category": "Verbal Ability",
        "option_a": "Something that appears bad but turns out good",
        "option_b": "A religious ceremony",
        "option_c": "A serious problem",
        "option_d": "A hidden person",
        "correct_answer": "A",
        "difficulty": "Hard",
    },
    {
        "question_text": "Choose the synonym of 'Diligent'.",
        "category": "Verbal Ability",
        "option_a": "Lazy",
        "option_b": "Hardworking",
        "option_c": "Careless",
        "option_d": "Weak",
        "correct_answer": "B",
        "difficulty": "Hard",
    },
    {
        "question_text": "Choose the antonym of 'Concise'.",
        "category": "Verbal Ability",
        "option_a": "Brief",
        "option_b": "Short",
        "option_c": "Lengthy",
        "option_d": "Precise",
        "correct_answer": "C",
        "difficulty": "Hard",
    },
    {
    "question_text": "Choose the word that best completes the sentence: The manager asked the employees to ___ the report before submitting it.",
    "category": "Verbal Ability",
    "option_a": "review",
    "option_b": "reviews",
    "option_c": "reviewed",
    "option_d": "reviewing",
    "correct_answer": "A",
    "difficulty": "Medium",
    },
    {
        "question_text": "Choose the correct meaning of 'Hit the nail on the head'.",
        "category": "Verbal Ability",
        "option_a": "Make a mistake",
        "option_b": "Say exactly the right thing",
        "option_c": "Work with tools",
        "option_d": "Avoid a problem",
        "correct_answer": "B",
        "difficulty": "Hard",
    },
]


def seed_questions():
    db = SessionLocal()

    try:
        db.query(models.Question).filter(
            models.Question.category == "Verbal Ability"
        ).delete(synchronize_session=False)

        db.commit()

        for question in questions:
            db.add(models.Question(**question))

        db.commit()

        count = db.query(models.Question).filter(
            models.Question.category == "Verbal Ability"
        ).count()

        print(f"Verbal Ability questions in database: {count}")

    except Exception as error:
        db.rollback()
        print(f"Error adding questions: {error}")

    finally:
        db.close()


if __name__ == "__main__":
    seed_questions()