from database import SessionLocal
import models


questions = [
    {
        "question_text": "A sum of money amounts to ₹14,400 in 2 years and ₹17,280 in 4 years at compound interest. What is the annual rate of interest?",
        "option_a": "8%",
        "option_b": "10%",
        "option_c": "12%",
        "option_d": "15%",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A train 240 m long crosses a platform 360 m long in 30 seconds. What is the speed of the train?",
        "option_a": "60 km/h",
        "option_b": "72 km/h",
        "option_c": "80 km/h",
        "option_d": "90 km/h",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "If x + 1/x = 5, what is the value of x^3 + 1/x^3?",
        "option_a": "110",
        "option_b": "115",
        "option_c": "120",
        "option_d": "125",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A mixture contains milk and water in the ratio 7:3. If 20 litres of the mixture are removed and replaced with water, the ratio becomes 7:5. What was the original quantity of the mixture?",
        "option_a": "100 litres",
        "option_b": "120 litres",
        "option_c": "140 litres",
        "option_d": "160 litres",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "The average of 11 consecutive integers is 42. What is the product of the smallest and largest integers?",
        "option_a": "1313",
        "option_b": "1320",
        "option_c": "1333",
        "option_d": "1344",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A and B can complete a task in 12 days and 18 days respectively. They work together for 4 days, after which A leaves. How many additional days will B need to finish the remaining work?",
        "option_a": "6",
        "option_b": "7",
        "option_c": "8",
        "option_d": "9",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "How many distinct arrangements can be made using all the letters of the word 'ASSESSMENT'?",
        "option_a": "151200",
        "option_b": "302400",
        "option_c": "453600",
        "option_d": "604800",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A box contains 5 red, 4 blue and 3 green balls. Three balls are drawn without replacement. What is the probability that all three are of different colors?",
        "option_a": "3/11",
        "option_b": "5/22",
        "option_c": "15/44",
        "option_d": "7/22",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A shopkeeper marks an article 40% above cost price and gives successive discounts of 10% and 15%. What is his profit percentage?",
        "option_a": "5%",
        "option_b": "7.1%",
        "option_c": "8%",
        "option_d": "10%",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "The roots of x^2 - 7x + k = 0 differ by 3. What is the value of k?",
        "option_a": "8",
        "option_b": "10",
        "option_c": "12",
        "option_d": "14",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A man travels 40% of a journey at 60 km/h and the remaining distance at 90 km/h. What is his average speed for the entire journey?",
        "option_a": "72 km/h",
        "option_b": "75 km/h",
        "option_c": "76.5 km/h",
        "option_d": "78 km/h",
        "correct_answer": "A",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "If 20% of a number exceeds 15% of the same number by 45, what is the number?",
        "option_a": "750",
        "option_b": "800",
        "option_c": "850",
        "option_d": "900",
        "correct_answer": "D",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "The HCF of two numbers is 18 and their LCM is 540. If one number is 90, what is the other number?",
        "option_a": "96",
        "option_b": "108",
        "option_c": "120",
        "option_d": "126",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A population increases by 20% in the first year and decreases by 10% in the second year. If the final population is 21,600, what was the initial population?",
        "option_a": "18,000",
        "option_b": "19,000",
        "option_c": "20,000",
        "option_d": "22,000",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "If the sum of the first n terms of an arithmetic progression is 3n^2 + 2n, what is the 10th term?",
        "option_a": "53",
        "option_b": "59",
        "option_c": "61",
        "option_d": "65",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A vessel contains 80 litres of alcohol and water in the ratio 3:1. How much water must be added to make the ratio 3:2?",
        "option_a": "15 litres",
        "option_b": "20 litres",
        "option_c": "25 litres",
        "option_d": "30 litres",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "What is the remainder when 7^103 is divided by 13?",
        "option_a": "5",
        "option_b": "6",
        "option_c": "7",
        "option_d": "8",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A committee of 5 people is to be selected from 6 men and 5 women. In how many ways can the committee be formed with at least 3 women?",
        "option_a": "281",
        "option_b": "286",
        "option_c": "291",
        "option_d": "296",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A person invests ₹20,000 partly at 8% and the rest at 12% simple interest. If the total annual interest is ₹2,160, how much was invested at 8%?",
        "option_a": "₹7,000",
        "option_b": "₹8,000",
        "option_c": "₹9,000",
        "option_d": "₹10,000",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "If log₂(x) + log₂(x - 2) = 3, what is x?",
        "option_a": "2",
        "option_b": "3",
        "option_c": "4",
        "option_d": "5",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A clock gains 5 minutes every 2 hours. If it is set correctly at 8:00 AM, what time will it show at 8:00 PM the same day?",
        "option_a": "8:25 PM",
        "option_b": "8:30 PM",
        "option_c": "8:35 PM",
        "option_d": "8:40 PM",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "The diagonal of a rectangle is 25 cm and its length is 5 cm more than its breadth. What is its area?",
        "option_a": "150 cm²",
        "option_b": "180 cm²",
        "option_c": "240 cm²",
        "option_d": "300 cm²",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A sum becomes ₹13,310 in 3 years at 10% compound interest. What was the principal?",
        "option_a": "₹8,000",
        "option_b": "₹9,000",
        "option_c": "₹10,000",
        "option_d": "₹11,000",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "Two pipes can fill a tank in 20 minutes and 30 minutes respectively. A third pipe can empty it in 60 minutes. If all three are opened together, how long will it take to fill the tank?",
        "option_a": "12 minutes",
        "option_b": "15 minutes",
        "option_c": "18 minutes",
        "option_d": "20 minutes",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "If 3x + 2y = 17 and 5x - 3y = 4, what is x + y?",
        "option_a": "5",
        "option_b": "6",
        "option_c": "7",
        "option_d": "8",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A car's speed is increased by 25%. By what percentage must the travel time be reduced to cover the same distance?",
        "option_a": "15%",
        "option_b": "20%",
        "option_c": "25%",
        "option_d": "30%",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "The sum of three consecutive odd numbers is 147. What is the square of the largest number?",
        "option_a": "2401",
        "option_b": "2500",
        "option_c": "2601",
        "option_d": "2704",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A number when divided by 5, 7 and 9 leaves remainders 2, 4 and 6 respectively. What is the smallest such positive number?",
        "option_a": "137",
        "option_b": "312",
        "option_c": "452",
        "option_d": "627",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A batsman has an average of 48 runs after 20 innings. What score must he make in the next innings to increase his average to 50?",
        "option_a": "80",
        "option_b": "88",
        "option_c": "90",
        "option_d": "92",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "If a:b = 3:4 and b:c = 8:9, what is a:c?",
        "option_a": "2:3",
        "option_b": "3:5",
        "option_c": "4:5",
        "option_d": "5:6",
        "correct_answer": "A",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A man sells two articles for ₹9,600 each. On one he gains 20% and on the other he loses 20%. What is the overall percentage loss?",
        "option_a": "2%",
        "option_b": "4%",
        "option_c": "5%",
        "option_d": "6%",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "How many positive integers less than 1000 are divisible by 3 or 5 but not both?",
        "option_a": "399",
        "option_b": "400",
        "option_c": "401",
        "option_d": "402",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A right triangle has legs 9 cm and 12 cm. What is the radius of its incircle?",
        "option_a": "2 cm",
        "option_b": "3 cm",
        "option_c": "4 cm",
        "option_d": "5 cm",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A person spends 75% of his income. His income increases by 20% while his expenditure increases by 10%. By what percentage do his savings increase?",
        "option_a": "40%",
        "option_b": "45%",
        "option_c": "50%",
        "option_d": "55%",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "If the roots of x² - px + 16 = 0 are positive integers differing by 6, what is p?",
        "option_a": "8",
        "option_b": "10",
        "option_c": "12",
        "option_d": "14",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A work can be completed by 8 men in 15 days. After 5 days, 4 men leave. How many more days are required to complete the remaining work?",
        "option_a": "15",
        "option_b": "18",
        "option_c": "20",
        "option_d": "22",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "The compound interest on a certain sum for 2 years at 10% per annum is ₹2,310. What is the principal?",
        "option_a": "₹10,000",
        "option_b": "₹10,500",
        "option_c": "₹11,000",
        "option_d": "₹11,500",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A die is thrown three times. What is the probability of obtaining at least one six?",
        "option_a": "25/36",
        "option_b": "91/216",
        "option_c": "125/216",
        "option_d": "135/216",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "If 2^x = 8^(x-2), what is x?",
        "option_a": "2",
        "option_b": "3",
        "option_c": "4",
        "option_d": "5",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A shopkeeper uses a 900 g weight while claiming to sell 1 kg and also charges 5% above the cost price. What is his effective profit percentage?",
        "option_a": "16.67%",
        "option_b": "20%",
        "option_c": "21.67%",
        "option_d": "25%",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "The present ages of A and B are in the ratio 5:7. After 6 years, the ratio becomes 3:4. What is B's present age?",
        "option_a": "18",
        "option_b": "21",
        "option_c": "24",
        "option_d": "28",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "What is the smallest positive integer that leaves remainder 5 when divided by 8, 12 and 15?",
        "option_a": "105",
        "option_b": "115",
        "option_c": "125",
        "option_d": "145",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "If the area of a circle is numerically equal to its circumference, what is its radius?",
        "option_a": "1 unit",
        "option_b": "2 units",
        "option_c": "π units",
        "option_d": "4 units",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A sum is divided among A, B and C in the ratio 2:3:5. If C receives ₹2,400 more than A, what is the total sum?",
        "option_a": "₹7,200",
        "option_b": "₹8,000",
        "option_c": "₹9,600",
        "option_d": "₹12,000",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A man can row 12 km downstream in 1 hour and the same distance upstream in 2 hours. What is the speed of the stream?",
        "option_a": "3 km/h",
        "option_b": "4 km/h",
        "option_c": "5 km/h",
        "option_d": "6 km/h",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A cylinder has radius 7 cm and height 10 cm. What is its curved surface area? Use π = 22/7.",
        "option_a": "420 cm²",
        "option_b": "440 cm²",
        "option_c": "460 cm²",
        "option_d": "480 cm²",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "In how many ways can 6 people be seated around a circular table if two particular people must not sit together?",
        "option_a": "48",
        "option_b": "60",
        "option_c": "72",
        "option_d": "84",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "If a number is increased by 30% and then decreased by 30%, the final value is 147 less than the original. What was the original number?",
        "option_a": "1,500",
        "option_b": "1,600",
        "option_c": "1,633.33",
        "option_d": "1,700",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "A and B invest ₹40,000 and ₹60,000 respectively. After 6 months, A withdraws half of his investment. If the annual profit is ₹22,000, what is B's share?",
        "option_a": "₹14,000",
        "option_b": "₹15,000",
        "option_c": "₹16,000",
        "option_d": "₹17,000",
        "correct_answer": "C",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
    {
        "question_text": "The sum of the first 20 terms of an arithmetic progression is 610 and its first term is 2. What is its common difference?",
        "option_a": "2",
        "option_b": "3",
        "option_c": "4",
        "option_d": "5",
        "correct_answer": "B",
        "category": "Quantitative",
        "difficulty": "Advanced",
    },
]


def seed_questions():
    db = SessionLocal()

    try:
        db.query(models.Question).filter(
            models.Question.category == "Quantitative"
        ).delete(synchronize_session=False)

        db.commit()

        for question in questions:
            db.add(models.Question(**question))

        db.commit()

        count = db.query(models.Question).filter(
            models.Question.category == "Quantitative"
        ).count()

        print(f"Quantitative questions in database: {count}")

    except Exception as error:
        db.rollback()
        print(f"Error adding questions: {error}")

    finally:
        db.close()


if __name__ == "__main__":
    seed_questions()