from database import SessionLocal
import models


questions = [
    {
        "question_text": "Find the next number: 2, 4, 8, 16, ?",
        "category": "Logical Reasoning",
        "option_a": "24",
        "option_b": "32",
        "option_c": "34",
        "option_d": "36",
        "correct_answer": "B",
        "difficulty": "Easy",
    },
    {
        "question_text": "Find the next number: 3, 6, 12, 24, ?",
        "category": "Logical Reasoning",
        "option_a": "36",
        "option_b": "42",
        "option_c": "48",
        "option_d": "54",
        "correct_answer": "C",
        "difficulty": "Easy",
    },
    {
        "question_text": "Find the odd one out: Apple, Mango, Carrot, Banana",
        "category": "Logical Reasoning",
        "option_a": "Apple",
        "option_b": "Mango",
        "option_c": "Carrot",
        "option_d": "Banana",
        "correct_answer": "C",
        "difficulty": "Easy",
    },
    {
        "question_text": "If CAT is coded as DBU, how is DOG coded?",
        "category": "Logical Reasoning",
        "option_a": "EPH",
        "option_b": "EOH",
        "option_c": "FPH",
        "option_d": "DPG",
        "correct_answer": "A",
        "difficulty": "Easy",
    },
    {
        "question_text": "Find the next letter: A, C, E, G, ?",
        "category": "Logical Reasoning",
        "option_a": "H",
        "option_b": "I",
        "option_c": "J",
        "option_d": "K",
        "correct_answer": "B",
        "difficulty": "Easy",
    },
    {
        "question_text": "If all roses are flowers and some flowers are red, which statement is definitely true?",
        "category": "Logical Reasoning",
        "option_a": "All roses are red",
        "option_b": "Some roses are red",
        "option_c": "All roses are flowers",
        "option_d": "No flowers are roses",
        "correct_answer": "C",
        "difficulty": "Easy",
    },
    {
        "question_text": "Find the missing number: 5, 10, 20, 40, ?",
        "category": "Logical Reasoning",
        "option_a": "60",
        "option_b": "70",
        "option_c": "80",
        "option_d": "90",
        "correct_answer": "C",
        "difficulty": "Easy",
    },
    {
        "question_text": "A is taller than B. B is taller than C. Who is the shortest?",
        "category": "Logical Reasoning",
        "option_a": "A",
        "option_b": "B",
        "option_c": "C",
        "option_d": "Cannot determine",
        "correct_answer": "C",
        "difficulty": "Easy",
    },
    {
        "question_text": "Find the odd one out: 2, 4, 6, 9, 10",
        "category": "Logical Reasoning",
        "option_a": "2",
        "option_b": "6",
        "option_c": "9",
        "option_d": "10",
        "correct_answer": "C",
        "difficulty": "Easy",
    },
    {
        "question_text": "If BOOK is coded as CPPL, how is PEN coded?",
        "category": "Logical Reasoning",
        "option_a": "QFO",
        "option_b": "QEN",
        "option_c": "PFN",
        "option_d": "RFO",
        "correct_answer": "A",
        "difficulty": "Easy",
    },

    {
        "question_text": "Find the next number: 1, 4, 9, 16, ?",
        "category": "Logical Reasoning",
        "option_a": "20",
        "option_b": "25",
        "option_c": "30",
        "option_d": "36",
        "correct_answer": "B",
        "difficulty": "Easy",
    },
    {
        "question_text": "Find the next number: 10, 20, 30, 40, ?",
        "category": "Logical Reasoning",
        "option_a": "45",
        "option_b": "50",
        "option_c": "55",
        "option_d": "60",
        "correct_answer": "B",
        "difficulty": "Easy",
    },
    {
        "question_text": "Which word does not belong? Dog, Cat, Cow, Rose",
        "category": "Logical Reasoning",
        "option_a": "Dog",
        "option_b": "Cat",
        "option_c": "Cow",
        "option_d": "Rose",
        "correct_answer": "D",
        "difficulty": "Easy",
    },
    {
        "question_text": "If A is the brother of B and B is the sister of C, how is A related to C?",
        "category": "Logical Reasoning",
        "option_a": "Brother",
        "option_b": "Sister",
        "option_c": "Father",
        "option_d": "Mother",
        "correct_answer": "A",
        "difficulty": "Easy",
    },
    {
        "question_text": "Find the next letter: B, D, F, H, ?",
        "category": "Logical Reasoning",
        "option_a": "I",
        "option_b": "J",
        "option_c": "K",
        "option_d": "L",
        "correct_answer": "B",
        "difficulty": "Easy",
    },
    {
        "question_text": "If today is Monday, what day will it be after 10 days?",
        "category": "Logical Reasoning",
        "option_a": "Wednesday",
        "option_b": "Thursday",
        "option_c": "Friday",
        "option_d": "Saturday",
        "correct_answer": "B",
        "difficulty": "Easy",
    },
    {
        "question_text": "Find the next number: 100, 90, 80, 70, ?",
        "category": "Logical Reasoning",
        "option_a": "50",
        "option_b": "55",
        "option_c": "60",
        "option_d": "65",
        "correct_answer": "C",
        "difficulty": "Easy",
    },
    {
        "question_text": "Which is different from the others? Square, Triangle, Circle, Cube",
        "category": "Logical Reasoning",
        "option_a": "Square",
        "option_b": "Triangle",
        "option_c": "Circle",
        "option_d": "Cube",
        "correct_answer": "D",
        "difficulty": "Easy",
    },
    {
        "question_text": "If 1 = A, 2 = B, 3 = C, what is 4?",
        "category": "Logical Reasoning",
        "option_a": "C",
        "option_b": "D",
        "option_c": "E",
        "option_d": "F",
        "correct_answer": "B",
        "difficulty": "Easy",
    },
    {
        "question_text": "Find the missing number: 7, 14, 21, 28, ?",
        "category": "Logical Reasoning",
        "option_a": "32",
        "option_b": "35",
        "option_c": "36",
        "option_d": "42",
        "correct_answer": "B",
        "difficulty": "Easy",
    },

    {
        "question_text": "Find the next number: 2, 5, 10, 17, ?",
        "category": "Logical Reasoning",
        "option_a": "24",
        "option_b": "25",
        "option_c": "26",
        "option_d": "27",
        "correct_answer": "C",
        "difficulty": "Medium",
    },
    {
        "question_text": "Find the next number: 1, 1, 2, 3, 5, ?",
        "category": "Logical Reasoning",
        "option_a": "6",
        "option_b": "7",
        "option_c": "8",
        "option_d": "9",
        "correct_answer": "C",
        "difficulty": "Medium",
    },
    {
        "question_text": "If TABLE is coded as UBCMF, how is CHAIR coded?",
        "category": "Logical Reasoning",
        "option_a": "DIBJS",
        "option_b": "DIBIR",
        "option_c": "DHAJS",
        "option_d": "EIBJS",
        "correct_answer": "A",
        "difficulty": "Medium",
    },
    {
        "question_text": "A man walks 5 km north and then 3 km east. In which direction is he from the starting point?",
        "category": "Logical Reasoning",
        "option_a": "North-East",
        "option_b": "North-West",
        "option_c": "South-East",
        "option_d": "South-West",
        "correct_answer": "A",
        "difficulty": "Medium",
    },
    {
        "question_text": "Find the odd number: 11, 13, 17, 19, 21",
        "category": "Logical Reasoning",
        "option_a": "11",
        "option_b": "17",
        "option_c": "19",
        "option_d": "21",
        "correct_answer": "D",
        "difficulty": "Medium",
    },
    {
        "question_text": "If all pens are objects and all objects have weight, what follows?",
        "category": "Logical Reasoning",
        "option_a": "All pens have weight",
        "option_b": "No pens have weight",
        "option_c": "Some objects are not pens",
        "option_d": "All objects are pens",
        "correct_answer": "A",
        "difficulty": "Medium",
    },
    {
        "question_text": "Find the next number: 4, 9, 19, 39, ?",
        "category": "Logical Reasoning",
        "option_a": "69",
        "option_b": "79",
        "option_c": "89",
        "option_d": "99",
        "correct_answer": "B",
        "difficulty": "Medium",
    },
    {
        "question_text": "A is older than B, B is older than C, and C is older than D. Who is youngest?",
        "category": "Logical Reasoning",
        "option_a": "A",
        "option_b": "B",
        "option_c": "C",
        "option_d": "D",
        "correct_answer": "D",
        "difficulty": "Medium",
    },
    {
        "question_text": "Find the next letter: Z, X, V, T, ?",
        "category": "Logical Reasoning",
        "option_a": "R",
        "option_b": "S",
        "option_c": "Q",
        "option_d": "P",
        "correct_answer": "A",
        "difficulty": "Medium",
    },
    {
        "question_text": "If SOUTH is written as HTUOS, how is NORTH written?",
        "category": "Logical Reasoning",
        "option_a": "HTRON",
        "option_b": "HTORN",
        "option_c": "NHTRO",
        "option_d": "TRONH",
        "correct_answer": "A",
        "difficulty": "Medium",
    },

    {
        "question_text": "Find the missing number: 3, 8, 15, 24, ?",
        "category": "Logical Reasoning",
        "option_a": "30",
        "option_b": "32",
        "option_c": "35",
        "option_d": "36",
        "correct_answer": "C",
        "difficulty": "Medium",
    },
    {
        "question_text": "Find the next number: 81, 27, 9, 3, ?",
        "category": "Logical Reasoning",
        "option_a": "0",
        "option_b": "1",
        "option_c": "2",
        "option_d": "4",
        "correct_answer": "B",
        "difficulty": "Medium",
    },
    {
        "question_text": "If EARTH is coded as FBSUI, how is WORLD coded?",
        "category": "Logical Reasoning",
        "option_a": "XPSME",
        "option_b": "XQSME",
        "option_c": "WPSME",
        "option_d": "YPSNF",
        "correct_answer": "A",
        "difficulty": "Medium",
    },
    {
        "question_text": "A person faces east, turns right, then turns right again. Which direction is he facing?",
        "category": "Logical Reasoning",
        "option_a": "North",
        "option_b": "South",
        "option_c": "East",
        "option_d": "West",
        "correct_answer": "D",
        "difficulty": "Medium",
    },
    {
        "question_text": "Which number is different? 4, 9, 16, 25, 30",
        "category": "Logical Reasoning",
        "option_a": "4",
        "option_b": "16",
        "option_c": "25",
        "option_d": "30",
        "correct_answer": "D",
        "difficulty": "Medium",
    },
    {
        "question_text": "If some students are athletes and all athletes are fit, what can be concluded?",
        "category": "Logical Reasoning",
        "option_a": "Some students are fit",
        "option_b": "All students are fit",
        "option_c": "No students are fit",
        "option_d": "All fit people are students",
        "correct_answer": "A",
        "difficulty": "Medium",
    },
    {
        "question_text": "Find the next number: 6, 12, 24, 48, ?",
        "category": "Logical Reasoning",
        "option_a": "72",
        "option_b": "84",
        "option_c": "96",
        "option_d": "108",
        "correct_answer": "C",
        "difficulty": "Medium",
    },
    {
        "question_text": "If MONDAY is coded as NPOEBZ, how is FRIDAY coded?",
        "category": "Logical Reasoning",
        "option_a": "GSJEBZ",
        "option_b": "GSJECZ",
        "option_c": "GRJEBZ",
        "option_d": "FSJEBZ",
        "correct_answer": "A",
        "difficulty": "Medium",
    },
    {
        "question_text": "A is to the left of B. C is to the right of B. Who is in the middle?",
        "category": "Logical Reasoning",
        "option_a": "A",
        "option_b": "B",
        "option_c": "C",
        "option_d": "Cannot determine",
        "correct_answer": "B",
        "difficulty": "Medium",
    },
    {
        "question_text": "Find the next letter: C, F, I, L, ?",
        "category": "Logical Reasoning",
        "option_a": "M",
        "option_b": "N",
        "option_c": "O",
        "option_d": "P",
        "correct_answer": "C",
        "difficulty": "Medium",
    },

    {
        "question_text": "Find the next number: 5, 11, 23, 47, ?",
        "category": "Logical Reasoning",
        "option_a": "83",
        "option_b": "91",
        "option_c": "95",
        "option_d": "99",
        "correct_answer": "C",
        "difficulty": "Hard",
    },
    {
        "question_text": "Find the next number: 2, 6, 12, 20, 30, ?",
        "category": "Logical Reasoning",
        "option_a": "40",
        "option_b": "42",
        "option_c": "44",
        "option_d": "46",
        "correct_answer": "B",
        "difficulty": "Hard",
    },
    {
        "question_text": "If each letter is shifted two positions forward, what is the code for LOGIC?",
        "category": "Logical Reasoning",
        "option_a": "NQIKE",
        "option_b": "NQIKE",
        "option_c": "NQGKE",
        "option_d": "MQIKE",
        "correct_answer": "A",
        "difficulty": "Hard",
    },
    {
        "question_text": "A person walks 4 km north, 4 km east, 4 km south, and 4 km west. Where is the person relative to the starting point?",
        "category": "Logical Reasoning",
        "option_a": "4 km north",
        "option_b": "4 km east",
        "option_c": "At the starting point",
        "option_d": "4 km west",
        "correct_answer": "C",
        "difficulty": "Hard",
    },
    {
        "question_text": "Find the odd one out: 8, 27, 64, 100, 125",
        "category": "Logical Reasoning",
        "option_a": "8",
        "option_b": "27",
        "option_c": "100",
        "option_d": "125",
        "correct_answer": "C",
        "difficulty": "Hard",
    },
    {
        "question_text": "If P is taller than Q, Q is taller than R, and S is taller than P, who is tallest?",
        "category": "Logical Reasoning",
        "option_a": "P",
        "option_b": "Q",
        "option_c": "R",
        "option_d": "S",
        "correct_answer": "D",
        "difficulty": "Hard",
    },
    {
        "question_text": "Find the next number: 7, 10, 16, 28, 52, ?",
        "category": "Logical Reasoning",
        "option_a": "88",
        "option_b": "96",
        "option_c": "100",
        "option_d": "104",
        "correct_answer": "D",
        "difficulty": "Hard",
    },
    {
        "question_text": "If all A are B and no B are C, which statement is definitely true?",
        "category": "Logical Reasoning",
        "option_a": "No A are C",
        "option_b": "All C are A",
        "option_c": "Some A are C",
        "option_d": "All B are A",
        "correct_answer": "A",
        "difficulty": "Hard",
    },
    {
        "question_text": "Find the next letter: A, D, H, M, ?",
        "category": "Logical Reasoning",
        "option_a": "R",
        "option_b": "S",
        "option_c": "T",
        "option_d": "U",
        "correct_answer": "B",
        "difficulty": "Hard",
    },
    {
        "question_text": "A clock shows 3:00. What is the angle between the hour and minute hands?",
        "category": "Logical Reasoning",
        "option_a": "45 degrees",
        "option_b": "60 degrees",
        "option_c": "90 degrees",
        "option_d": "120 degrees",
        "correct_answer": "C",
        "difficulty": "Hard",
    },
]


def seed_questions():
    db = SessionLocal()

    try:
        db.query(models.Question).filter(
            models.Question.category == "Logical Reasoning"
        ).delete(synchronize_session=False)

        db.commit()

        for question in questions:
            db.add(models.Question(**question))

        db.commit()

        count = db.query(models.Question).filter(
            models.Question.category == "Logical Reasoning"
        ).count()

        print(f"Logical Reasoning questions in database: {count}")

    except Exception as error:
        db.rollback()
        print(f"Error adding questions: {error}")

    finally:
        db.close()


if __name__ == "__main__":
    seed_questions()